# Generated by Django 2.1 on 2018-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20181019_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
