# Generated by Django 2.1 on 2018-11-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_base64',
            field=models.TextField(null=True),
        ),
    ]
